---
- name: Add VLANs to device
  hosts: switch1
  tasks:
    - name: Add VLANs
      arista.eos.eos_vlans:
        config:
          - name: "{{ item.name }}"
            vlan_id: "{{ item.vlan_id }}"
            state: active
        state: merged
      loop: "{{ vlans }}"
      